FROM golang:1.17 as build

WORKDIR /go/src/app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /app {{ .BuildDirectory }}

FROM public.ecr.aws/lambda/go:1
COPY --from=build /app ${LAMBDA_TASK_ROOT}
CMD ["/app"]
